# Xamarin
#
# Template that contains the different steps required to run device
# tests. The template takes a number of parameters so that it can
# be configured for the different type of devices.
#

parameters:

- name: statusContext
  type: string 
  default: 'iOS Device Tests' # default context, since we started dealing with iOS devices. 

- name: testsLabels
  type: string 
  default: '--label=run-ios-64-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests' # default context, since we started dealing with iOS devices. 

- name: disableProviCleanup
  type: boolean
  default: false

- name: clearProviCache
  type: boolean
  default: false

steps:

- checkout: self
- checkout: maccore
  persistCredentials: true

- pwsh: |
    Import-Module ./scripts/System.psm1
    Get-SystemInfo | Format-Table -Wrap -HideTableHeaders
  displayName: 'Dump Environment'
  timeoutInMinutes: 1

- pwsh: |
    Import-Module ./scripts/System.psm1
    Clear-HD 
  displayName: 'Disk cleanup'
  timeoutInMinutes: 5

- pwsh: |
    Import-Module ./scripts/System.psm1
    Import-Module ./scripts/VSTS.psm1
    Import-Module ./scripts/GitHub.psm1
    if ( -not Test-HDFreeSpace -Size 50) {
      Set-GitHubStatus -Status "error" -Description "Not enough free space in the host." -Context "$Env:CONTEXT"
      New-GitHubComment -Header "Tests failed catastrophically" -Emoji ":fire:" -Message "Not enough free space in the host."
      Stop-Pipeline
    }
  env:
      CONTEXT: ${{ parameters.statusContext}}
  displayName: 'Check HD Free Space'
  timeoutInMinutes: 5

# if we got to this point, it means that we do have at least 50 Gb to run the test, should
# be more than enough, else the above script would have stop the pipeline
- bash: cd xamarin-macios && ./configure --enable-xamarin
  displayName: 'Enable Xamarin'
  timeoutInMinutes: 1

- bash: |
    set -x
    set -e
    rm -f ~/Library/Caches/com.xamarin.provisionator/Provisions/*p12
    rm -f ~/Library/Caches/com.xamarin.provisionator/Provisions/*mobileprovision
    ./maccore/tools/install-qa-provisioning-profiles.sh -v 
  displayName: 'Add provisioning profiles'
  env:
    LOGIN_KEYCHAIN_PASSWORD: $(OSX_KEYCHAIN_PASS)

- pwsh: |
    Import-Module ./scripts/VSTS.psm1
    Import-Module ./scripts/GitHub.psm1
    Set-GitHubStatus -Status "error" -Description "Failed provisioning profiles." -Context "$Env:CONTEXT"
    New-GitHubComment -Header "Tests failed catastrophically" -Emoji ":fire:" -Message "Failed provisioning profiles."
    Stop-Pipeline
  env:
      CONTEXT: ${{ parameters.statusContext}}
  condition: failed() # we could not provisiong, we stop the pipeline, there is not point in doing anything else
  timeoutInMinutes: 5

- bash: make -C $(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/ device-tests-provisioning.csx
  displayName: 'Generate Provisionator csx file'

# TODO: do not use a path with a user name!
- bash: rm -rf "/Users/xamarinqa/azdo/_work/_tool/provisionator"
  displayName: 'Nuke Provisionator Tool Cache'
  condition: ${{ parameters.clearProviCache }}

- task: xamops.azdevex.provisionator-task.provisionator@1
  displayName: 'Provision dependencies'
  inputs:
    provisioning_script: $(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/device-tests-provisioning.csx
    provisioning_extra_args: '-vvvv'
  timeoutInMinutes: 250

- pwsh: |
    Import-Module ./scripts/VSTS.psm1
    Import-Module ./scripts/GitHub.psm1
    Set-GitHubStatus -Status "error" -Description "Failed installing dependencies." -Context "$Env:CONTEXT"
    New-GitHubComment -Header "Tests failed catastrophically" -Emoji ":fire:" -Message "Failed installing dependencies."
    Stop-Pipeline
  env:
      CONTEXT: ${{ parameters.statusContext}}
  condition: failed() # we could not install the deps, set comments and leave
  timeoutInMinutes: 5

- pwsh : |
    Import-Module ./scripts/System.psm1
    Clear-XamarinProcesses 
  displayName: 'Process cleanup'

- bash: |
    security set-key-partition-list -S apple-tool:,apple: -s -k $(OSX_KEYCHAIN_PASS) login.keychain
  displayName: 'Remove security UI-prompt (http://stackoverflow.com/a/40039594/183422)'
  condition: succeededOrFailed() # we do not care about the previous process cleanup

- pwsh : |
    Import-Module ./scripts/MLaunch.psm1
    Set-MLaunchVerbosity -Verbosity "1234567890"
  displayName: 'Make mlaunch verbose'
  condition: succeededOrFailed() # we do not care about the previous step 

- pwsh : |
    Import-Module ./scripts/MLaunch.psm1
    Optimize-DeviceDiscovery 
  displayName: 'Fix device discovery (reset launchctl)'
  condition: succeededOrFailed() # making mlaunch verbose should be a non blocker

- pwsh: |
    Import-Module ./scripts/GitHub.psm1 
    Set-GitHubStatus -Status "pending" -Context $Env:CONTEXT -Description "Running device tests on $Env:CONTEXT"
  env:
      CONTEXT: ${{ parameters.statusContext}}
  displayName: Set pending GitHub status
  continueOnError: true
  condition: succeededOrFailed() # re-starting the daemon should not be an issue
  timeoutInMinutes: 5

- bash: |
    set -x
    set -e

    P=$(cat tmp.p)

    ssh builder@xamarin-storage "mkdir -p /volume1/storage/$P"
    export TESTS_PERIODIC_COMMAND="--periodic-interval 10 --periodic-command rsync --periodic-command-arguments '-avz -e \"ssh\" $PWD/jenkins-results builder@xamarin-storage:/volume1/storage/$P'"

    make -C builds downloads -j || true
    make -C builds .stamp-mono-ios-sdk-destdir -j || true

    MONO_ENV_OPTIONS=--trace=E:all make -C tests vsts-device-tests
  env:
      TESTS_EXTRA_ARGUMENTS: ${{ parameters.testsLabels }}
  displayName: 'Run tests'
  timeoutInMinutes: 600

- bash: |
    set +x
    
    X="#vso"
    echo help
    
    FILE=$PWD/tests/TestSummary.md
    if ! test -f $FILE; then
    echo "# Tests failed catastrophically (no summary found)" > $FILE
    fi
    
    echo "#$X[task.addattachment type=Distributedtask.Core.Summary;name=Test results;]$FILE"
    
    echo "[Wrench lane]($WRENCH_URL)" > Wrench.md
    echo "#$X[task.addattachment type=Distributedtask.Core.Summary;name=Wrench;]$PWD/Wrench.md"
  displayName: 'Add summaries'
  condition: always()
  timeoutInMinutes: 1

- task: PublishTestResults@2
  displayName: 'Publish NUnit Device Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: '**/vsts-*.xml'
    failTaskOnFailedTests: true
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: HtmlReport'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/HtmlReport-$(Build.BuildId).zip'
    artifactName: HtmlReport
  continueOnError: true
  condition: succeededOrFailed()

# TODO: Move to vsdrops!!!
- bash: |
    set -e
    set -x
    
    P=$(cat tmp.p)
    
    ssh -i ~/.ssh/release-manager-rsa builder@xamarin-storage mkdir -p /volume1/storage/$P
    rsync -avz -e "ssh -i ~/.ssh/release-manager-rsa" jenkins-results builder@xamarin-storage:/volume1/storage/$P
  displayName: 'Upload HtmlReport to Boston Storage'
  condition: always()

- bash: |
    sudo rm -rf /Applications/Visual\ Studio*
    rm -rf ~/Library/Caches/VisualStudio
    rm -rf ~/Library/Logs/VisualStudio
    rm -rf ~/Library/VisualStudio
    rm -rf ~/Library/Preferences/Xamarin/
    rm -rf ~/Library/Caches/com.xamarin.provisionator
  displayName: 'Cleanup'
  continueOnError: true
  condition: always() # no matter what, includes cancellation