# Runs the device tests on iOS beta devices.
resources:
  repositories:
  - repository: maccore
    type: github
    name: xamarin/maccore
    ref: refs/heads/device-tests-yaml # should this be on a branch and not on master???
    endpoint: xamarin

variables:
  - group: xamops-azdev-secrets
  - template: templates/variables.yml

stages:
- stage: device_tests
  jobs:
  - job: tests
    displayName: 'Run iOS Beta Device Tests'
    timeoutInMinutes: 1000
    pool:
      name: "VSEng-Xamarin-QA"
      demands: "xismoke-beta" 
    steps:
    - template: templates/device-tests.yml
      parameters:
        testsLabels: '--label=run-ios-64-tests,run-non-monotouch-tests,run-monotouch-tests,run-mscorlib-tests'
        statusContext: 'VSTS: device tests iOS'
