# imports the xml to the vsts test results for the job
parameters:

- name: testPrefix
  type: string 
  default: 'ios' # default context, since we started dealing with iOS devices. 

# did the provisioning work?
- name: provisioningFailed
  type: string 
  default: 'False'

- name: isPR
  type: boolean

steps:

- template: checkout.yml
  parameters:
    isPR: ${{ parameters.isPR }}

- ${{ if eq(parameters.provisioningFailed, 'False') }}:
  - template: download-artifacts.yml 
    parameters:
      testPrefix: ${{ parameters.testPrefix }}

  # Upload test results to vsts.
  - task: PublishTestResults@2
    displayName: 'Publish NUnit Device Test Results'
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/vsts-*.xml'
      failTaskOnFailedTests: true
    continueOnError: true
    condition: succeededOrFailed()
